'use client';

import { useEffect } from 'react';

// ─────────────────────────────────────────────────────────────────────────────
// Generated by Surge AI
// Stack: Next.js 14 · TypeScript · Tailwind CSS
//
// This page renders the AI-generated website using dangerouslySetInnerHTML so
// that the Tailwind CDN classes, custom CSS, and vanilla JS all work as-is.
//
// To convert this to proper TSX components:
//   1. Break the HTML body into React components in src/components/
//   2. Replace dangerouslySetInnerHTML with JSX
//   3. Move styles to Tailwind classes or CSS modules
//   4. Remove the Tailwind CDN <Script> from layout.tsx
// ─────────────────────────────────────────────────────────────────────────────

const pageBody = `

    <!-- Navigation -->
    <nav class="bg-white bg-opacity-50 backdrop-blur-md fixed w-full z-10 top-0">
        <div class="max-w-7xl mx-auto px-4 py-3 flex justify-between items-center">
            <div class="text-2xl font-bold text-deep-red">Your Restaurant Name</div>
            <ul class="hidden md:flex space-x-4">
                <li><a href="#home" class="hover:text-gold">Home</a></li>
                <li><a href="#menu" class="hover:text-gold">Menu</a></li>
                <li><a href="#reservation" class="hover:text-gold">Reservation</a></li>
                <li><a href="#about" class="hover:text-gold">About</a></li>
                <li><a href="#contact" class="hover:text-gold">Contact</a></li>
            </ul>
            <button class="md:hidden text-deep-red focus:outline-none">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" class="w-6 h-6">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M4 6h16M4 12h16m-7 6h7" />
                </svg>
            </button>
        </div>
    </nav>

    <!-- Hero Section -->
    <section id="home" class="hero h-screen flex items-center justify-center">
        <div class="text-center text-white">
            <h1 class="text-6xl font-bold mb-4">Discover the Flavors of South India</h1>
            <p class="text-xl">Indulge in authentic cuisine with a modern twist.</p>
        </div>
    </section>

    <!-- Menu Section -->
    <section id="menu" class="menu-section px-4 py-16">
        <div class="max-w-7xl mx-auto">
            <h2 class="text-4xl font-bold mb-4">Our Menu</h2>
            <p class="text-lg mb-8">Explore our diverse range of South Indian delicacies.</p>
            <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                <div class="bg-white p-4 rounded-lg shadow-md">
                    <img onerror="this.onerror=null;this.src='https://source.unsplash.com/1600x1000/?Dosa&sig=101';" loading="lazy" src="https://images.unsplash.com/photo-1498654896293-37aacf113fd9?auto=format&fit=crop&w=800&q=80" alt="Dosa" class="w-full h-48 object-cover rounded-t-lg">
                    <h3 class="text-2xl font-bold mt-4">Dosa</h3>
                    <p class="text-gray-600">Crispy and savory, served with chutneys.</p>
                    <p class="text-lg font-bold mt-2">₹100</p>
                </div>
                <div class="bg-white p-4 rounded-lg shadow-md">
                    <img onerror="this.onerror=null;this.src='https://source.unsplash.com/1600x1000/?Idli&sig=102';" loading="lazy" src="https://images.unsplash.com/photo-1617191512007-872a1d501d5b?auto=format&fit=crop&w=800&q=80" alt="Idli" class="w-full h-48 object-cover rounded-t-lg">
                    <h3 class="text-2xl font-bold mt-4">Idli</h3>
                    <p class="text-gray-600">Steamed rice cakes, a healthy choice.</p>
                    <p class="text-lg font-bold mt-2">₹80</p>
                </div>
                <div class="bg-white p-4 rounded-lg shadow-md">
                    <img onerror="this.onerror=null;this.src='https://source.unsplash.com/1600x1000/?Biryani&sig=103';" loading="lazy" src="https://images.unsplash.com/photo-1562967916-eb82221dfb02?auto=format&fit=crop&w=800&q=80" alt="Biryani" class="w-full h-48 object-cover rounded-t-lg">
                    <h3 class="text-2xl font-bold mt-4">Biryani</h3>
                    <p class="text-gray-600">Aromatic and flavorful, a royal dish.</p>
                    <p class="text-lg font-bold mt-2">₹150</p>
                </div>
            </div>
        </div>
    </section>

    <!-- Reservation Section -->
    <section id="reservation" class="reservation-section px-4 py-16 bg-white">
        <div class="max-w-7xl mx-auto">
            <h2 class="text-4xl font-bold mb-4">Make a Reservation</h2>
            <p class="text-lg mb-8">Book your table for an exquisite dining experience.</p>
            <img onerror="this.onerror=null;this.src='https://source.unsplash.com/1600x1000/?Restaurant%2CInterior&sig=104';" loading="lazy" src="https://images.unsplash.com/photo-1555992336-03a23c0c7f3e?auto=format&fit=crop&w=1600&q=90" alt="Restaurant Interior" class="w-full h-64 object-cover rounded-lg mb-8">
            <!-- Add reservation form here -->
        </div>
    </section>

    <!-- About Section -->
    <section id="about" class="about-section px-4 py-16">
        <div class="max-w-7xl mx-auto">
            <h2 class="text-4xl font-bold mb-4">About Us</h2>
            <p class="text-lg mb-8">Learn more about our story and what makes us unique.</p>
            <div class="grid grid-cols-1 md:grid-cols-3 gap-4">
                <img onerror="this.onerror=null;this.src='https://source.unsplash.com/1600x1000/?Chef&sig=105';" loading="lazy" src="https://images.unsplash.com/photo-1506368004600-1a83113e6c8d?auto=format&fit=crop&w=800&q=80" alt="Chef" class="w-full h-48 object-cover rounded-lg">
                <img onerror="this.onerror=null;this.src='https://source.unsplash.com/1600x1000/?Restaurant&sig=106';" loading="lazy" src="https://images.unsplash.com/photo-1499028344343-cd173ffc68a9?auto=format&fit=crop&w=800&q=80" alt="Restaurant" class="w-full h-48 object-cover rounded-lg">
                <img onerror="this.onerror=null;this.src='https://source.unsplash.com/1600x1000/?Ingredients&sig=107';" loading="lazy" src="https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=800&q=80" alt="Ingredients" class="w-full h-48 object-cover rounded-lg">
            </div>
        </div>
    </section>

    <!-- Contact Section -->
    <section id="contact" class="contact-section px-4 py-16">
        <div class="max-w-7xl mx-auto">
            <h2 class="text-4xl font-bold mb-4">Contact Us</h2>
            <div class="flex flex-col lg:flex-row space-y-6 lg:space-y-0 lg:space-x-12">
                <div class="w-full lg:w-1/2">
                    <p class="text-lg mb-2">Address: Velachery, Chennai, India</p>
                    <p class="text-lg mb-2">Phone: +91 7010190110</p>
                    <p class="text-lg mb-4">Email: support@workfast.ai</p>
                    <div class="h-64 mb-8">
                        <iframe src="https://www.google.com/maps/embed/v1/place?key=YOUR_API_KEY&q=Velachery,Chennai,India" class="w-full h-full rounded-lg" allowfullscreen></iframe>
                    </div>
                </div>
                <div class="w-full lg:w-1/2">
                    <form class="space-y-4">
                        <input type="text" placeholder="Name" class="w-full px-4 py-2 border rounded-lg">
                        <input type="tel" placeholder="Phone" class="w-full px-4 py-2 border rounded-lg">
                        <textarea placeholder="Message" class="w-full px-4 py-2 border rounded-lg" rows="4"></textarea>
                        <button type="submit" class="w-full py-2 bg-deep-red text-white rounded-lg hover:bg-gold transition">Send Message</button>
                    </form>
                </div>
            </div>
        </div>
    </section>

`;
const pageScripts = ``;

export default function Home() {
  useEffect(() => {
    if (!pageScripts.trim()) return;
    try {
      const script = document.createElement('script');
      script.textContent = pageScripts;
      document.body.appendChild(script);
      return () => {
        try { document.body.removeChild(script); } catch (_) {}
      };
    } catch (e) {
      console.warn('Script execution warning:', e);
    }
  }, []);

  return (
    <div dangerouslySetInnerHTML={{ __html: pageBody }} />
  );
}
